version: "3"

services:

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - gateway

    gateway:
        image: shipyardsuite/gateway:develop
        container_name: gateway
        ports:
            - "8080:8080"
            - "80:80"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./gateway/config/system.config.yml:/usr/src/app/config/system.config.yml
            - ./gateway/config/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        networks:
            - gateway

    auth:
        image: shipyardsuite/auth:develop
        command: sh -c 'npm run start'
        container_name: auth
        ports:
            - "3002:3002"
        networks:
            - gateway
        environment:
            SERVICE_NAME: auth
            SERVICE_PORT: 3002

    user:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: user
        ports:
            - "3009:3009"
        networks:
            - gateway
        environment:
            SERVICE_PORT: 3009
            SERVICE_NAME: user

networks:
    gateway:
