http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    template:
        host: localhost
        paths: [ '/template/*', '/template/api/*', '/template/images/*', '/template/uploads/*']
    notfound:
        host: localhost
        paths: [ '/notfound/*' ]
serviceEndpoints:
    template:
        url: 'http://template:3000'
    notfound:
        url: 'http://notfound:3003'
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    template:
        apiEndpoints:
            - template
        policies:
            - proxy:
                - action:
                    serviceEndpoint: template 
                    changeOrigin: true
    notfound:
        apiEndpoints:
            - notfound
        policies:
            - proxy:
                - action:
                    serviceEndpoint: notfound 
                    changeOrigin: true
